### ISSUE TITLE
JUB always POSTs to localhost:3000

### ISSUE THREAD

**Issue by tkw1536** [OpenJUB/jRooms#1]
@filipbitola says its your fault @dmitryfd

**Comment by dmitryfd** [comment]
Fair, that shouldn't be a problem to fix.
Thanks for noticing!

**Comment by dmitryfd** [comment]
It actually can already be set at openjub.js, in JUB.url. It will stay localhost:3000 for now for testing purposes, but to actually fix it, we can either get the server's address or just change that variable.

**Comment by tkw1536** [comment]
@dmitryfd Sounds like a fine argument, but can't you just replace it with: 
```
location.protocol+'//'+location.hostname+(location.port ? ':'+location.port: '');
```

**Comment by dmitryfd** [comment]
That is also true. I was considering the setup where frontend and API wouldn't be hosted on a same server/port or where different sub domains would be applied.
I will change it to your suggestion with the next commit.
